/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#e8eff1",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#0a1d2f",
        "background": "#f4fafd",
        "on-primary-fixed": "#002018",
        "secondary": "#785a00",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#3e4945",
        "error-container": "#ffdad6",
        "inverse-surface": "#2b3234",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#80d7bb",
        "surface-container-highest": "#dde4e6",
        "surface-container-high": "#e2e9ec",
        "on-primary": "#ffffff",
        "secondary-container": "#fdd26e",
        "tertiary-fixed": "#d2e4fd",
        "surface-container-low": "#eef5f7",
        "surface-tint": "#006b56",
        "on-secondary-fixed": "#251a00",
        "primary-container": "#5cb399",
        "inverse-primary": "#80d7bb",
        "surface-bright": "#f4fafd",
        "inverse-on-surface": "#ebf2f4",
        "surface": "#f4fafd",
        "on-secondary-fixed-variant": "#5b4300",
        "outline": "#6e7a74",
        "tertiary-fixed-dim": "#b6c8e0",
        "on-primary-fixed-variant": "#005140",
        "surface-variant": "#dde4e6",
        "tertiary": "#4f6075",
        "primary": "#006b56",
        "on-tertiary-fixed-variant": "#37485c",
        "on-secondary": "#ffffff",
        "on-surface": "#161d1f",
        "on-secondary-container": "#765900",
        "primary-fixed": "#9cf3d7",
        "surface-dim": "#d4dbdd",
        "on-background": "#161d1f",
        "outline-variant": "#bec9c3",
        "on-tertiary-container": "#2a3b4e",
        "tertiary-container": "#94a5bc",
        "secondary-fixed-dim": "#ebc160",
        "on-primary-container": "#004234",
        "secondary-fixed": "#ffdf9b"
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "base": "8px",
        "margin-desktop": "40px",
        "container-max": "1280px",
        "gutter": "24px",
        "card-padding": "24px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "body-md": ["Montserrat", "sans-serif"],
        "body-lg": ["Montserrat", "sans-serif"],
        "headline-xl": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "headline-sm": ["Montserrat", "sans-serif"],
        "label-sm": ["Montserrat", "sans-serif"],
        "label-md": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "body-sm": ["Montserrat", "sans-serif"],
        "arabic-brand": ["Vazirmatn", "sans-serif"]
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries")
  ],
};
